### ISSUE TITLE
.well-known/acme-challenge is not created or cert not installed.

### ISSUE THREAD

**Issue by ghost** [imbrish/letsencrypt#4]
At least I think that's the problem.  Installation went fine. 

Here's the output from bin/letsencrypt (I modified the expire to 91 so it would run a second time). 

```
ricksID@servername [~/letsencrypt]$ bin/letsencrypt
'/opt/alt/php56/usr/bin/php' '/home/ricksID/letsencrypt/bin/acme' 'setup' '--email' 'letsencrypt@ricksdomain.com' '--server' 'letsencrypt' '--storage' '/home/ricksID/letsencrypt/storage'
Using existing private key ...
    Registering with acme-v01.api.letsencrypt.org/directory ...
    Registration successful. Contacts: mailto:letsencrypt@corwyn.net
'/opt/alt/php56/usr/bin/php' '/home/ricksID/letsencrypt/bin/acme' 'check' '--name' 'ricksdomain.net' '--ttl' '91' '--names' 'ricksdomain.net,www.ricksdomain.net' '--server' 'letsencrypt' '--storage' '/home/ricksID/letsencrypt/storage'
Certificate is valid until 16.09.2018

    Certificate is going to expire within the specified 91 days.
'/opt/alt/php56/usr/bin/php' '/home/ricksID/letsencrypt/bin/acme' 'issue' '--domains' 'ricksdomain.net:www.ricksdomain.net' '--path' '/home/ricksID/public_html/www.ricksdomain.net:/home/ricksID/public_html/www.ricksdomain.net' '--bits' '4096' '--server' 'letsencrypt' '--storage' '/home/ricksID/letsencrypt/storage'
Providing payload at http://ricksdomain.net/.well-known/acme-challenge/18ZrkzA947gTmoWrI2ubQNyMp9j1XJ1Gvbp-oPfiw2M
    Providing payload at http://www.ricksdomain.net/.well-known/acme-challenge/V9dDR2GTG-Rfa3AKt948EPi7EGjwJTDXD3oYZ7aLTck
    ricksdomain.net is now authorized.
    www.ricksdomain.net is now authorized.

    Requesting certificate ...
    Successfully issued certificate.
    See /home/ricksID/letsencrypt/storage/certs/acme-v01.api.letsencrypt.org.directory/ricksdomain.net
Certificate issued for domains: ricksdomain.net, www.ricksdomain.net.
```

I went ahead and created the directories, but they don't seem to populate. The files are in /home/ricksID/letsencrypt/storage/certs/acme-v01.api.letsencrypt.org.directory/ricksdomain.net
They do not show up in the GoDaddy Manage SSH Keys page. 

It could relate to the fact that I'm trying to add the keys for a sub domain? I don't know. 

I'm aware that I'll have to update the .htaccess file, but I need the certs to install first.

**Comment by imbrish** [comment]
Hey! 

First of all you shouldn't be uploading your config file anywhere because it contains sensitive data (like your CPanel user/password). I removed it from your comment, but once published it's not safe anymore thus I strongly recommend that you change your password.

Regarding your problem it seems that issuing of a new certificate goes well, which rules out `.htaccess` issues. The installation however is not even attempted, because you added `ricksdomain.net` to the install blacklist, which means that the domain should be skipped.

To fix it just go ahead and leave both `whitelist` and `blacklist` sections of `install` empty. This will automatically install certificates for all domains mentioned in the `certificates` section.

**Comment by ghost** [comment]
Good catch, I thought I'd anonymized everything; I got the folder and domain name, just not the account. Sigh. 

Will try that - thanks.

**Comment by imbrish** [comment]
You can re-run the command after updating the config, it should re-use the already issued certificates just for the installation.

I clarified the configuration options in the config example and readme :) Hope everything goes well and good luck with your project!
